// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Child: typeof import('./src/components/Child.vue')['default']
    CountCard: typeof import('./src/components/CountCard.vue')['default']
    CountComposableCard: typeof import('./src/components/CountComposableCard.vue')['default']
    CounterCard: typeof import('./src/components/CounterCard.vue')['default']
    CountMixinCard: typeof import('./src/components/CountMixinCard.vue')['default']
    EtcComp: typeof import('./src/components/EtcComp.vue')['default']
    Expose: typeof import('./src/components/Expose.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetupContext: typeof import('./src/components/SetupContext.vue')['default']
    Vue2_options: typeof import('./src/components/vue2_options.vue')['default']
  }
}
